### PR TITLE
Flask: add PATCH /api/users/:username

### LINKED ISSUE #188: Redesign administration page
User stories
- [x] As an administrator, I want to see last login times and activation status of all users.
- [x] As an administrator, I want to view and reset MinIO credentials for any user on demand.
- [x] As an administrator, I want to activate and deactivate users on demand.
- [x] As an administrator, I want to see what groups any user belongs to and add or remove them from those groups.

### LINKED ISSUE #193: Epic: /api/users
Existing endpoints in `routes.py` should be moved out to a new `users.py`

- [x] Update **GET /api/users** (list_users)
  Admin-only. Returns an array of JSON objects of the username, email, admin status, last login, activation status, and an array of group codes.

- [x] **GET /api/users/:username** (get_user)
   Regular users may query themselves. Admins can query all users. Returns a JSON of the username, email, admin status, an array of group codes, last login, activation status, MinIO access key, and MinIO secret key. This is the same as list_users but also includes the MinIO credentials, which need to be added as fields to the User model.

- [x] Update **POST /api/users** (create_user)
  Admin-only. Creates a new user with the specified credentials, email, admin status, groups. Also creates a MinIO identity and assigns it to those groups. Return result matches GET /api/users/:username. Return the new URL in the Location header.

- [x] **PATCH /api/users/:username** (update_user)
  Replaces PUT /api/users and POST /api/password. If the requesting user is an admin, this updates the affected fields (excluding MinIO credentials). If the username is changed, return the new URL in the Location header. Deactivating users deletes the MinIO identity. Activating users recreates it. Fail the request with 404 if any of the new group_codes do not exist. The response should have the same format as get_user.
  If the requesting user is a regular user, the behaviour of this endpoint should match the old /api/password: they are only allowed to change their own password and must provide their old password as well.

- [x] **POST /api/users/:username** (reset_minio_user)
  Resets the MinIO credentials for this user (i.e. delete the MinIO user and create a new one with membership in the same groups) to a new randomly-generated pair and returns them. Regular users may do this for themselves and admins may do this for any user.

- [x] **DELETE /api/users/:username** (delete_user)
  Replaces DELETE /api/users. Admin-only. Deletes the user, including their MinIO identity. If anything in the database other than group membership depends on the user existing, fail the request with 422.

### PR DESCRIPTION
**Pull request by kevinlul**
Replaces PUT /api/users and POST /api/password
Hook up to frontend

Closes #193
Closes #188

### CODE REVIEW

**Comment by Madelinehazel** [comment]
I might be missing something, but I don't see a way to deactivate a user from the frontend; there's just an 'Active User' box that isn't responsive.

**Comment by kevinlul** [comment]
Is your frontend up-to-date? I changed that in this PR too.

**Comment by Madelinehazel** [comment]
I pulled your branch, so it should be up to date (and then `yarn` and `yarn start`); is there anything else i'd need to do?

**Review by Madelinehazel — APPROVED** [review]
LGTM

**Review by frewmack — CHANGES_REQUESTED** [review]
Admin page looks good to me. However the endpoint on the Settings page needs to be updated as POST /api/password is no longer used.

**Comment by kevinlul** [comment]
Good catch, there's actually a bit more on the frontend to change.

**Review by frewmack — APPROVED** [review]
Looks good to me!

**Pull request merged**
