### PR TITLE
Docker: lock MinIO to previous version to fix CI failures

### PR DESCRIPTION
**Pull request by kevinlul**
minio/minio#11544

Should unblock all backend PRs

### CODE REVIEW

**Review by frewmack — APPROVED** [review]
LGTM!

**Comment by kevinlul** [comment]
It's still broken though 😭

**Comment by kevinlul** [comment]
It was both MinIO and the command-line client...

**Review by frewmack — APPROVED** [review]
Good catch! Backend checks pass so I think we're clear.

**Pull request merged**
