### PR TITLE
Flask: implement progressive loading and filtering on /api/datasets

### PR DESCRIPTION
**Pull request by kevinlul**
#283

### CODE REVIEW

**Comment by kevinlul** [comment]
Just discovered that the `updated_by` filter doesn't work. Working on it

**Comment by frewmack** [comment]
Having an issue filtering by dataset_type. Looking into it right now
```
curl "http://localhost:3000/api/datasets?dataset_type=RGS&page=0&limit=10"
{
  "error": "__init__() takes 1 positional argument but 2 were given"
}
```

**Comment by kevinlul** [comment]
This is my mistake. DatasetType isn't an enum anymore, so it's trying to call the initializer for an entity rather than an enum.

**Comment by kevinlul** [comment]
I think I should add more comprehensive test cases for the new behaviours but it could take some time.

**Review by frewmack — APPROVED** [review]
Looks good to me! Frontend filtering works as expected.

**Pull request merged**
