### PR TITLE
CI: Use pytest-cov to measure code coverage

### PR DESCRIPTION
**Pull request by jennyziyi-xu**
`Pytest-cov:` https://pytest-cov.readthedocs.io/en/latest/readme.html

### CODE REVIEW

**Comment by kevinlul** [comment]
Need to change the command used in .github/workflows/flask.yml to get coverage results on CI.

Furthermore, I know of two neat sites (Coveralls and CodeCov) that can integrate with GitHub Actions and LCOV reports, but that requires a little more work and maybe some extra volumes or environment variables passed around as our tests are in a Docker container.

**Comment by kevinlul** [comment]
I can work on the latter part (adding coveralls or codecov) if you'd like, or send the tabs I have your way.

**Comment by jennyziyi-xu** [comment]
Sounds good! Feel free to work on the latter part. Either way works for me.

**Comment by kevinlul** [comment]
https://app.codecov.io/gh/ccmbioinfo/stager/branch/jenny%2Fpytest-coverage

**Review by kevinlul — APPROVED** [review]

**Pull request merged**
