### PR TITLE
Flask/React: clean-up for pipeline automation

### PR DESCRIPTION
**Pull request by kevinlul**
Remove pipelines as a database table as we need specific code to implement; embed the categories of datasets in code rather than outside of code in a database table.

Backend changes:
- remove tables DatasetType, MetaDatasetType, MetaDatasetType_DatasetType, Pipeline, PipelineDatasets
- rename Analysis.qsub_id to Analysis.scheduler_id
- replace Analysis.pipeline_id with Analysis.kind
- remove migrations that explicitly refer to the current SQLAlchemy models (do not do this as it makes the migrations depend on model code)
- remove old one-time click commands that depend on removed tables
- remove /api/pipelines
- remove /api/metadatasettypes
- remove /api/enums
- add the info from those endpoints to /api
- add dataset type dictionary with currently-supported types
- enforce the dataset type constraint for POST /api/_bulk and POST /api/datasets via marshmallow
- update pipeline check in POST /api/analyses to a dataset type compatibility check based on "kind"

Frontend changes
- remove enums and metadatasettypes hooks, useAPIInfoContext instead
- remove enums prop drilling for a bunch of components
- remove pipeline selection from analysis request dialogue
- replace analysis table pipeline filter with kind filter
- update analysis info dialogue with scheduler ID and remove pipeline stuff
- hack together a replacement for the enums passed to getOptions in DataEntryTable, to replace in later PRs

Todo:
- [x] test migration on replicas of production databases
- [x] frontend: remove getOptions enums dependency

#1055

### CODE REVIEW

**Comment by kevinlul** [comment]
Backend changes should be done

**Comment by jennyziyi-xu** [comment]
LGTM. Reviewed the code and tested the following features:

- On Add Datasets page, choose field values from options in the dropdown.
- Run analysis with datasets of the same kind succeeds. The job's standard output can be viewed on HPC. 
- Run analysis with datasets of different kinds fails. 
- Inspected the `Dataset`, `Analysis`, and other tables in the database to compare with changes mentioned in this PR.
- Tested the upgrade migration. Not testing downgrade in the migration because it's not intended to work.

**Review by jennyziyi-xu — APPROVED** [review]

**Review by delvinso — APPROVED** [review]
LGTM! Tested migration with production data and analysis submissions on the front end. Data integrity looks good as well.

**Review by hannahle — COMMENTED** [review]
The rest LGTM!

**Comment by kevinlul** [comment]
Everything looks good in prod

**Pull request merged**
