### PR TITLE
Flask: made unlinked file query non-recursive to reduce payload

### PR DESCRIPTION
**Pull request by hannahle**
The goal of this PR is to reduce the `unlinked` file's endpoint payload. 

The main changes in this PR are:
- Set `recursive` property to `false`
- Added a check to see if an option is a file or folder. If it's a folder, autocomplete the folder path and sends off a query. If not, then the file is selected as an unlinked file.

### CODE REVIEW

**Comment by jennyziyi-xu** [comment]
The user cannot start the input path with a "/". If the user inputs `/cheo/`, the error message will be displayed: "Bucket name must be one of ...". In this case, the user might not know where is the problem because "cheo" is among the list of suggested bucket names. It might be better to allow the flexibility of this leading slash, although this is a minor issue.

**Comment by kevinlul** [comment]
We didn't support the leading slash to begin with; it's syntactically incorrect.

**Comment by kevinlul** [comment]
This approach seems effective, but behaviour feels a little funky when just using the keyboard to navigate. Suggested text in the textbox and the options sometimes disappear when moving around with arrow keys.

**Comment by jennyziyi-xu** [comment]
For me, when just using the keyboard to navigate (left and right arrow keys), the options disappear but would come back if I press up or down arrow keys.

**Comment by kevinlul** [comment]
I'm not expecting the dropdown to change. I thought it might be because of the altered stale time but that doesn't seem to be it.

**Comment by hannahle** [comment]
> I'm not expecting the dropdown to change. I thought it might be because of the altered stale time but that doesn't seem to be it.

Ah nope, the stale time just makes the data "stale" after 1s and allows for a re-query.

**Review by kevinlul — APPROVED** [review]
Okayed by collabs 🙏 🎉 ⌛

**Pull request merged**
