### PR TITLE
React/Flask: Fix datasets editing modal (#814)

### PR DESCRIPTION
**Pull request by jennyziyi-xu**
Subtask 4: For the following fields, when the limit is hit, the user cannot type into the field anymore. Sequencing Center (string max len 100) 
Batch ID (string max len 50) 
Extraction Protocol (string max len 100) 
Capture Kit (string max len 50) 
Library Prep Method (string max len 50) 
Read length (string max len 10, length of the maximum integer)

( Notes (TEXT object, do not have a length limit).) 

Subtask 5: Implement type validation for `read_length` only, `read_length` must only contain digits, as other fields are either objects or can be alphanumeric. My only concern is if making the type validation in `onChange()` would slow down the rendering. I hypothesize that this is not an issue because `error` and `helperText` are props for TextField in Material UI, so they should be already optimized. 

Subtask 6: `onUpdate() ` is a function that we want to refactor in this sprint. I think that the way we want to send `library_prep_date` to the backend may be different after refactoring `onUpdate() `. The code added may or may not be useful in the future.

### CODE REVIEW

**Review by kevinlul — APPROVED** [review]
Yeah that's all I have within the scope of this PR, since there's more work to do later

LGTM!

**Review by cklamann — CHANGES_REQUESTED** [review]
There's a 500 that gets thrown when I try to update a dataset with linked files. It seems that this is due to the same issue that's causing problems with `library_prep_date` updates--the modal is sending back the view representation (array of file path strings) rather than the model (array of `File` objects). I think for the time being it might be best to just disable this field, since the user can use the in-table editing controls anyway, until we have the modal refactor done and can add the `FileLinkingComponent`.

**Comment by jennyziyi-xu** [comment]
> There's a 500 that gets thrown when I try to update a dataset with linked files. It seems that this is due to the same issue that's causing problems with `library_prep_date` updates--the modal is sending back the view representation (array of file path strings) rather than the model (array of `File` objects). I think for the time being it might be best to just disable this field, since the user can use the in-table editing controls anyway, until we have the modal refactor done and can add the `FileLinkingComponent`.

Yes, good point. I am aware of this error and I think another ticket #836 addresses this issue. I will disable the field for now.

**Review by cklamann — APPROVED** [review]
:rocket:

**Pull request merged**
